name: designdino
description: "Design Dino"
version: 0.0.1-alpha.1
homepage: https://github.com/TahaTesser/designdino
repository: https://github.com/TahaTesser/designdino
issue_tracker: https://github.com/TahaTesser/designdino/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  shadcn_ui: ^0.27.4
  device_preview: ^1.2.0  
  # device_preview:
  #   git:
  #     url: https://github.com/aloisdeniel/flutter_device_preview.git
  #     ref: master
  #     path: device_preview
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
